Document: hidblock
Title: Debian hidblock Manual
Author: <insert document author here>
Abstract: This manual describes what hidblock is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hidblock/hidblock.sgml.gz

Format: postscript
Files: /usr/share/doc/hidblock/hidblock.ps.gz

Format: text
Files: /usr/share/doc/hidblock/hidblock.text.gz

Format: HTML
Index: /usr/share/doc/hidblock/html/index.html
Files: /usr/share/doc/hidblock/html/*.html
